# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'comm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\"r\n\x14\x43liCheckpointRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x14\n\x07payload\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x12\x15\n\x08\x66unction\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_payloadB\x0b\n\t_function\">\n\x11\x43liRestoreRequest\x12\x14\n\x0crestore_mode\x18\x01 \x01(\t\x12\x13\n\x0brestore_num\x18\x02 \x01(\x05\"A\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\",\n\x14\x43liPrepareEnvRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\"?\n\x14\x43liUploadFileRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x11\n\tfile_path\x18\x02 \x01(\t\"5\n\x18\x43liStartContainerRequest\x12\x19\n\x11\x63li_content_patch\x18\x01 \x01(\x0c\x32\xc8\x02\n\x11NodeCommunication\x12<\n\x11\x45xecuteCheckpoint\x12\x15.CliCheckpointRequest\x1a\x10.CommandResponse\x12\x36\n\x0e\x45xecuteRestore\x12\x12.CliRestoreRequest\x1a\x10.CommandResponse\x12\x39\n\x0e\x45xecutePrepare\x12\x15.CliPrepareEnvRequest\x1a\x10.CommandResponse\x12<\n\x11\x45xecuteUploadFile\x12\x15.CliUploadFileRequest\x1a\x10.CommandResponse\x12\x44\n\x15\x45xecuteStartContainer\x12\x19.CliStartContainerRequest\x1a\x10.CommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLICHECKPOINTREQUEST']._serialized_start=14
  _globals['_CLICHECKPOINTREQUEST']._serialized_end=128
  _globals['_CLIRESTOREREQUEST']._serialized_start=130
  _globals['_CLIRESTOREREQUEST']._serialized_end=192
  _globals['_COMMANDRESPONSE']._serialized_start=194
  _globals['_COMMANDRESPONSE']._serialized_end=259
  _globals['_CLIPREPAREENVREQUEST']._serialized_start=261
  _globals['_CLIPREPAREENVREQUEST']._serialized_end=305
  _globals['_CLIUPLOADFILEREQUEST']._serialized_start=307
  _globals['_CLIUPLOADFILEREQUEST']._serialized_end=370
  _globals['_CLISTARTCONTAINERREQUEST']._serialized_start=372
  _globals['_CLISTARTCONTAINERREQUEST']._serialized_end=425
  _globals['_NODECOMMUNICATION']._serialized_start=428
  _globals['_NODECOMMUNICATION']._serialized_end=756
# @@protoc_insertion_point(module_scope)
