# apiVersion: v1
# kind: Service
# metadata:
#   name: __app-name__-__stage-name__-__replica-id__
# spec:
#   type: LoadBalancer
#   ports:
#   - port: __worker-external-port__
#     targetPort: __worker-port__
#     name: worker
#   - port: __cache-server-external-port__
#     targetPort: __cache-server-port__
#     name: cache-server
#   selector:
#     app: __app-name__-__stage-name__-__replica-id__
#   externalIPs: 
#   - __external-ip__
# ---
apiVersion: v1
kind: Pod
metadata:
  name: __app-name__-s__stage-name__-ra__replica-id__-rt__repeat-id__
  labels:
    app: __app-name__-s__stage-name__-ra__replica-id__-rt__repeat-id__
spec:
  nodeSelector:
    kubernetes.io/hostname: __node-name__
  containers:
    - name: my-container
      image: __image__
      imagePullPolicy: IfNotPresent
      command: __command__
      args: __args__
      env:
        - name: REDIS_HOST
          value: __redis-host__ # Redis 主机地址
      ports:
        - name: worker # 对应 worker
          containerPort: __worker-port__ # 容器内 worker 服务的端口
          hostPort: __worker-external-port__ # 映射到主机的 worker 端口
          protocol: TCP
        - name: cache-server # 对应 cache-server
          containerPort: __cache-server-port__ # 容器内 cache server 服务的端口
          hostPort: __cache-server-external-port__ # 映射到主机的 cache server 端口
          protocol: TCP
      resources:
        requests:
          cpu: __cpurequest__
          nvidia.com/gpu: __gpurequest__
        limits:
          cpu: __cpurequest__
          nvidia.com/gpu: __gpurequest__
      volumeMounts:
      - name: spilot-redis-config
        readOnly: true
        mountPath: "/etc/spilot-redis-config"
  volumes:
  - name: spilot-redis-config
    secret:
      secretName: spilot-redis-config