apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis-pod
spec:
  containers:
  - args:
    - --port
    - '6379'
    - --requirepass
    - 293r9vfT7dfa&^
    image: redis
    imagePullPolicy: IfNotPresent
    name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  externalIPs:
  - 10.0.0.100
  ports:
  - port: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Secret
metadata:
  name: spilot-redis-config
stringData:
  redis-host: 10.0.0.100
  redis-password: 293r9vfT7dfa&^
  redis-port: '6379'
type: Opaque
