apiVersion: v1
kind: Service
metadata:
  name: __app-name__-__stage-name__
spec:
  type: LoadBalancer
  ports:
  - port: __worker-external-port__
    targetPort: __worker-port__
    name: worker
  - port: __cache-server-external-port__
    targetPort: __cache-server-port__
    name: cache-server
  selector:
    app: __app-name__-__stage-name__
  externalIPs: 
  - __external-ip__
---
apiVersion: v1
kind: Pod
metadata:
  name: __app-name__-__stage-name__
  labels:
    app: __app-name__-__stage-name__
spec:
  nodeSelector:
    kubernetes.io/hostname: __node-name__
  containers:
    - name: my-container
      image: __image__
      imagePullPolicy: IfNotPresent
      command: __command__
      args: __args__
      resources:
        requests:
          cpu: __r_vcpu__
        limits:
          cpu: __r_vcpu__
      securityContext:
        privileged: __privileged__
      volumeMounts:
      - name: spilot-redis-config
        readOnly: true
        mountPath: "/etc/spilot-redis-config"
  volumes:
  - name: spilot-redis-config
    secret:
      secretName: spilot-redis-config